#!/usr/bin/env bash

bazel run @unpinned_maven//:pin
jq -S '.dependency_tree.dependencies |= sort_by(.coord) | .dependency_tree.dependencies[].dependencies |= sort_by(.) | .dependency_tree.dependencies[].directDependencies |= sort_by(.)' maven/maven_install.json >tmp.json
mv tmp.json maven/maven_install.json
